//Handling Exception method2 in main


import java.io.IOException;


public class ThrowDemo
{
	public void method1()throws IOException
	{
		System.out.println("I am in method 1 ThrowDemo");
		method2();
	}
	

	public void method2()throws IOException
	{
		System.out.println("I am in method 2 ThrowDemo");
		
		throw new IOException();
	}
}


**************************************

import java.io.IOException;


public class TestThrowsDemo 
{

	public static void main(String[] args) 
	{
		ThrowDemo tt=new ThrowDemo();
		try {
			tt.method1();
	    } catch (IOException e) {
		e.printStackTrace();
	    }
	}
}
